[package]
name = "tensor4all-tensorci"
description = "Tensor Cross Interpolation algorithms for tensor4all"
version.workspace = true
edition.workspace = true
authors = ["Marc Ritter <Ritter.Marc@physik.uni-muenchen.de>", "Hiroshi Shinaoka <h.shinaoka@gmail.com>", "tensor4all contributors"]
license = "MIT"
repository.workspace = true

[dependencies]
num-complex.workspace = true
num-traits.workspace = true
anyhow.workspace = true
thiserror.workspace = true
rand.workspace = true
matrixci = { path = "../matrixci" }
tensor4all-simpletensortrain = { path = "../tensor4all-simpletensortrain" }

[dev-dependencies]
approx = "0.5"
criterion = "0.5"
bnum = "0.12"
uint = "0.10"

[[bench]]
name = "cached_function"
harness = false
