name = "Tensor4all"
uuid = "a1b2c3d4-e5f6-7890-abcd-ef1234567890"
version = "0.1.0"
authors = ["tensor4all collaboration"]

[deps]
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
RustToolChain = "e9dc52e2-edb8-4742-9783-5e542d30dbb5"

[weakdeps]
ITensors = "9136182c-28ba-11e9-034c-db9fb085ebd5"

[extensions]
Tensor4allITensorsExt = ["ITensors"]

[compat]
ITensors = "0.6, 0.7, 0.8, 0.9"
RustToolChain = "0.1"
julia = "1.9"

[extras]
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
ITensors = "9136182c-28ba-11e9-034c-db9fb085ebd5"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "ITensors", "HDF5"]
