[package]
name = "tensor4all-core-tensor"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
tensor4all-core-common = { path = "../common" }
num-complex.workspace = true
num-traits.workspace = true
mdarray.workspace = true
mdarray-linalg.workspace = true
anyhow.workspace = true
dyn-clone.workspace = true
rand.workspace = true
rand_distr.workspace = true

[dev-dependencies]
rand_chacha.workspace = true
